name: Deploy

on:
  workflow_run:
    workflows: ["python-app"]  
    types:
      - completed 

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H -p 8888 ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      # - name: connect
      #   run: ssh -p 8888 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Connect via SSH with password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 8888 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Pull Docker image and run container
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}  # Login to Docker Hub
          docker pull ${{ secrets.DOCKER_IMAGE }}  # Pull the image from Docker Hub
          docker run -d --name fastapi-app -p 8000:8000 ${{ secrets.DOCKER_IMAGE }}  # Run the container (example with Nginx)
      
      - name: cleanup
        run: rm -rf ~/.ssh
